export const TRANSLATIONS = {
  en: {
    appTitle: "PUNPORT FX", appSubtitle: "Analytics & Performance Metrics",
    clearFilters: "Clear Filters", addData: "Add Data / Settings",
    currentBalance: "Current Balance", initial: "Initial:", netPnL: "Net PnL", return: "Return",
    winRate: "Win Rate", trades: "Trades", maxDrawdown: "Max Drawdown", peakToTrough: "Peak to Trough drop",
    profitFactor: "Profit Factor", grossProfitLoss: "Gross Profit / Gross Loss", expectancy: "Expectancy ($)",
    perTrade: "per trade", avgRRR: "Average RRR", riskReward: "Risk Reward Ratio", avgHoldTime: "Avg Holding Time",
    entryExitDuration: "Duration", equityCurve: "Equity Curve & Drawdown", balance: "Balance", peak: "Peak",
    netPnLSystem: "Net PnL by System", netPnLSession: "Net PnL by Session", netPnLSetup: "Net PnL by Setup",
    netPnLDay: "Net PnL by Day (Mon-Fri)", netPnLAsset: "Net PnL by Asset", monthlyPnL: "Monthly PnL",
    yearlyPnL: "Yearly Profit & Loss", pnlByDuration: "PnL by Holding Time", profit: "Profit", loss: "Loss",
    clickToFilter: "Click bar to filter", filtered: "Filtered:", tradeLog: "Trade Log History", noTrades: "No trades found.",
    dateExit: "Date (Exit)", asset: "Asset", system: "System", dirTF: "Dir / TF", result: "Result",
    chart: "Chart", action: "Action", edit: "Edit", won: "Won", lost: "Lost", be: "BE",
    logTrade: "Log a Trade", editTrade: "Edit Trade ✨", accSettings: "Account Settings",
    entryDate: "Entry Date & Time", exitDate: "Exit Date & Time", direction: "Direction", buy: "Buy", sell: "Sell",
    timeframe: "TF", setup: "Setup", session: "Session", riskAmount: "Risk Amount ($)", rewardRatio: "Reward Ratio",
    auto: "Auto", chartUrl: "Chart Image URL (Optional)", saveTrade: "Save Trade", saveSettings: "Save Settings", initialCapital: "Initial Capital ($)",
    riskPerTrade: "Risk Per Trade (%)", settingsSaved: "Settings are saved automatically to your local storage.",
    simulateCompounding: "Simulate Compounding", compoundingDesc: "Recalculate all trades PnL dynamically based on starting capital, risk %, and R-Multiple.",
    Mon: "Mon", Tue: "Tue", Wed: "Wed", Thu: "Thu", Fri: "Fri",
    Jan: "Jan", Feb: "Feb", Mar: "Mar", Apr: "Apr", May: "May", Jun: "Jun", Jul: "Jul", Aug: "Aug", Sep: "Sep", Oct: "Oct", Nov: "Nov", Dec: "Dec",
    createProfile: "Create New Profile", profileName: "Profile Name", saveProfile: "Save Profile", mainPortfolio: "Main Portfolio", cancel: "Cancel",
    deleteProfile: "Delete Profile", confirmDeleteProfile: "Are you sure you want to delete this profile? All trade data and settings will be permanently lost.", delete: "Delete",
    switchProfile: "Switch Profile",
    emailNotAuthorized: "Email not authorized", authError: "Error checking authorization", verify: "Verify", enterEmailToUnlock: "Enter email to unlock features...",
    exportCSV: "Export CSV", importCSV: "Import CSV"
  },
  th: {
    appTitle: "PUNPORT FX", appSubtitle: "การวิเคราะห์และตัวชี้วัดประสิทธิภาพ",
    clearFilters: "ล้างตัวกรอง", addData: "เพิ่มข้อมูล / ตั้งค่า",
    currentBalance: "ยอดเงินปัจจุบัน", initial: "ทุนเริ่มต้น:", netPnL: "กำไร/ขาดทุนสุทธิ", return: "ผลตอบแทน",
    winRate: "อัตราการชนะ", trades: "ออเดอร์", maxDrawdown: "การลดลงสูงสุด", peakToTrough: "วัดจากจุดสูงสุดถึงต่ำสุด",
    profitFactor: "ปัจจัยกำไร", grossProfitLoss: "กำไรรวม / ขาดทุนรวม", expectancy: "ความคาดหวัง ($)",
    perTrade: "ต่อ 1 การเทรด", avgRRR: "RRR เฉลี่ย", riskReward: "สัดส่วนผลตอบแทน", avgHoldTime: "เวลาถือออเดอร์เฉลี่ย",
    entryExitDuration: "ระยะเวลาถือออเดอร์", equityCurve: "เส้นการเติบโตของพอร์ต & Drawdown", balance: "ยอดเงิน", peak: "จุดสูงสุด",
    netPnLSystem: "กำไร ($) แยกตามระบบ", netPnLSession: "กำไร ($) แยกตามช่วงเวลา", netPnLSetup: "กำไร ($) แยกตามเกรด Setup",
    netPnLDay: "กำไร ($) แยกตามวัน (จ.-ศ.)", netPnLAsset: "กำไร ($) แยกตามสินทรัพย์", monthlyPnL: "กำไร/ขาดทุน รายเดือน",
    yearlyPnL: "กำไร/ขาดทุน รายปี", pnlByDuration: "กำไร/ขาดทุน แยกตามระยะเวลาถือครอง", profit: "กำไร", loss: "ขาดทุน",
    clickToFilter: "คลิกที่กราฟแท่งเพื่อกรองข้อมูล", filtered: "กรองด้วย:", tradeLog: "ประวัติการเทรด", noTrades: "ไม่พบประวัติการเทรด",
    dateExit: "วันที่ (ปิดสถานะ)", asset: "สินทรัพย์", system: "ระบบ", dirTF: "ทิศทาง / TF", result: "ผลลัพธ์",
    chart: "กราฟ", action: "ลบ", edit: "แก้ไข", won: "ชนะ", lost: "แพ้", be: "เสมอ",
    logTrade: "บันทึกการเทรด", editTrade: "แก้ไขออเดอร์ ✨", accSettings: "ตั้งค่าบัญชี",
    entryDate: "วันและเวลาเข้าเทรด", exitDate: "วันและเวลาปิดสถานะ", direction: "ทิศทาง", buy: "ซื้อ (Buy)", sell: "ขาย (Sell)",
    timeframe: "TF", setup: "รูปแบบ (Setup)", session: "เซสชัน", riskAmount: "จำนวนเงินที่เสี่ยง ($)", rewardRatio: "สัดส่วนผลตอบแทน (RR)",
    auto: "คำนวณอัตโนมัติ", chartUrl: "ลิงก์รูปกราฟ (ถ้ามี)", saveTrade: "บันทึกข้อมูล", saveSettings: "บันทึกการตั้งค่า", initialCapital: "ทุนเริ่มต้น ($)",
    riskPerTrade: "ความเสี่ยงต่อไม้ (%)", settingsSaved: "การตั้งค่าจะถูกบันทึกลงในเครื่องอัตโนมัติ",
    simulateCompounding: "จำลองการทบต้น (Compounding)", compoundingDesc: "คำนวณกำไร/ขาดทุนใหม่ทั้งหมดตามทุนเริ่มต้น, % ความเสี่ยง และค่า R-Multiple",
    Mon: "จันทร์", Tue: "อังคาร", Wed: "พุธ", Thu: "พฤหัส", Fri: "ศุกร์",
    Jan: "ม.ค.", Feb: "ก.พ.", Mar: "มี.ค.", Apr: "เม.ย.", May: "พ.ค.", Jun: "มิ.ย.", Jul: "ก.ค.", Aug: "ส.ค.", Sep: "ก.ย.", Oct: "ต.ค.", Nov: "พ.ย.", Dec: "ธ.ค.",
    createProfile: "สร้างโปรไฟล์ใหม่", profileName: "ชื่อโปรไฟล์", saveProfile: "บันทึกโปรไฟล์", mainPortfolio: "พอร์ตหลัก", cancel: "ยกเลิก",
    deleteProfile: "ลบโปรไฟล์", confirmDeleteProfile: "คุณแน่ใจหรือไม่ว่าต้องการลบโปรไฟล์นี้? ข้อมูลการเทรดและการตั้งค่าทั้งหมดจะหายไปอย่างถาวร", delete: "ลบข้อมูล",
    switchProfile: "สลับโปรไฟล์",
    emailNotAuthorized: "อีเมลนี้ไม่ได้รับสิทธิ์เข้าใช้งาน", authError: "เกิดข้อผิดพลาดในการตรวจสอบสิทธิ์", verify: "ตรวจสอบ", enterEmailToUnlock: "กรอกอีเมลเพื่อปลดล็อกฟังก์ชัน...",
    exportCSV: "ส่งออก CSV", importCSV: "นำเข้า CSV"
  }
};

export const INITIAL_CAPITAL = 10000;
